architecture: "timm::tf_efficientnetv2_b1"
pretrained: True
format: "pascal_voc"
epochs: 100
lr: 0.0005
min_lr: 0.000005
n_cls: -1
wandb: True
img_size: 128
mosaic: False
task: classification
augmentations: True
whitening: False
